import React from 'react';
import { Download, RefreshCw, Maximize2 } from 'lucide-react';
import { Button } from './Button';

interface ResultDisplayProps {
  imageUrl: string | null;
  onDownload: () => void;
  onReset: () => void;
}

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ imageUrl, onDownload, onReset }) => {
  if (!imageUrl) return null;

  return (
    <div className="w-full animate-in fade-in duration-700">
      <div className="bg-modera-800/50 rounded-xl border border-modera-700 overflow-hidden">
        <div className="p-4 border-b border-modera-700 flex justify-between items-center bg-modera-900/50">
          <h3 className="text-white font-serif flex items-center gap-2">
            <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
            Studio Result
          </h3>
          <div className="flex gap-2">
             <Button variant="outline" onClick={onReset} className="!py-1 !px-3 text-xs h-8">
               <RefreshCw className="w-3 h-3 mr-1" /> New
             </Button>
          </div>
        </div>
        
        <div className="relative aspect-[3/4] w-full bg-black group">
           <img 
             src={imageUrl} 
             alt="Generated Model" 
             className="w-full h-full object-contain"
           />
           <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4 backdrop-blur-[1px]">
             <Button onClick={onDownload} variant="gold" className="shadow-xl">
               <Download className="w-5 h-5" /> Download 4K
             </Button>
             <button 
                onClick={() => window.open(imageUrl, '_blank')}
                className="p-3 bg-white/10 text-white rounded-full hover:bg-white/20 backdrop-blur-md"
             >
                <Maximize2 className="w-5 h-5" />
             </button>
           </div>
        </div>
      </div>
      <div className="mt-4 text-center text-xs text-slate-500">
        Generated by Modera AI Engine • Commercial License Included
      </div>
    </div>
  );
};